### ISSUE TITLE
Supabase v2 Types

### ISSUE THREAD

**Issue by drewbietron** [HermanNygaard/supabase-query#2]
Found this repo and found it very helpful, thank you for that!

This isn't an issue, but I was wondering if you've tried adapting this to the new v2 Supabase client?  In particular the Typescript portion that's been added.

I'm able to get the table names typed.
```typescript
type QueryCreator = (supabase: SupabaseClient<Database>) => PostgrestFilterBuilder<any, any>;
```
But getting the .select or other methods to be typed, as well as type the return value of the `UseQueryResult` have been pretty difficult.  Was wondering if you've had any luck with it.

Supabase is doing some sort of [TS voodoo](https://github.com/supabase/supabase-js/blob/master/src/SupabaseClient.ts#L156) to use the arguments passed to `.from` and it's a little over my head 🤯.

Appreciate any insight and thanks for creating this repo!

**Comment by HermanNygaard** [comment]
Hey @drewbietron , 

Thanks for your comment. I also agree with this and would love to see it, but got very limited time right now. If anyone is up for it please feel free to contribute.

**Comment by drewbietron** [comment]
@HermanNygaard - Looking at React Query support with this library.  Once the nut is cracked it could be applied to the context types here 💪 - https://github.com/psteinroe/supabase-cache-helpers/issues/57#issuecomment-1295259341

**Comment by HermanNygaard** [comment]
@drewbietron I'm thinking to start looking into this now (and then moving to `tanstack-query`). I see you already have done some work (linked in the thread above and in supabase-issues), looks promising. Do you have any updates or a quick summary on what the blocker is now? Also cool to see supabase-cache-helpers – I didn't know about that library.

**Comment by HermanNygaard** [comment]
I have started integrating v2 here #3, mostly done
